pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'java -jar /var/jenkins_home/workspace/maven-job/target/my-app-1.0-SNAPSHOT.jar'
            }
        }
    }
}
